name: docker-build-and-push
description: ""

inputs:
  bake-target:
    description: ""
    required: true
  build-args:
    description: ""
    required: false
  tag-prefix:
    description: ""
    required: false
  tag-suffix:
    description: ""
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install jq
      run: |
        sudo apt-get -y update
        sudo apt-get -y install jq
      shell: bash

    # workflow_dispatch: latest, date
    # schedule: latest, date
    # tag: semver
    - name: Set Docker tags
      id: set-docker-tags
      run: |
        tags=()
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          tags+=("latest")
          tags+=("{{date 'YYYYMMDD'}}")
        else
          tags+=("type=schedule,pattern=latest")
          tags+=("type=schedule,pattern={{date 'YYYYMMDD'}}")
          tags+=("type=semver,pattern={{version}}")
          tags+=("type=match,pattern=\d+.\d+")
        fi

        # Output multiline strings: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "tags<<$EOF" >> $GITHUB_OUTPUT
        echo "$(printf "%s\n" "${tags[@]}")" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Docker meta for devel
      id: meta-devel
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-devel
        flavor: |
          latest=false
          prefix=${{ inputs.tag-prefix }}
          suffix=${{ inputs.tag-suffix }}

    - name: Docker meta for prebuilt
      id: meta-prebuilt
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-prebuilt
        flavor: |
          latest=false
          prefix=${{ inputs.tag-prefix }}
          suffix=-prebuilt${{ inputs.tag-suffix }}

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push
      uses: docker/bake-action@v3
      with:
        # Checking event_name for https://github.com/autowarefoundation/autoware/issues/2796
        push: ${{ github.event_name == 'schedule' || github.ref_name == github.event.repository.default_branch || github.event_name == 'push'}}
        files: |
          docker/${{ inputs.bake-target }}/docker-bake.hcl
          ${{ steps.meta-devel.outputs.bake-file }}
          ${{ steps.meta-prebuilt.outputs.bake-file }}
        provenance: false
        set: |
          ${{ inputs.build-args }}
